[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["echo 'Dependencies will be installed by build script'"]

[phases.build]
cmds = ["bash railway-build.sh"]

[start]
cmd = "npm run start:prod"
